-- Keep an existing verification database compatible with the current
-- New Vendor intake / case-management frontend.
--
-- Run this once in the Supabase SQL Editor for projects created before the
-- frontend-intake extensions were added.

alter table public.verification_vendors
    add column if not exists region text,
    add column if not exists category text,
    add column if not exists categories text[] not null default '{}'::text[],
    add column if not exists contact_name text,
    add column if not exists contact_email text,
    add column if not exists contact_phone text,
    add column if not exists compliance_confirmed boolean,
    add column if not exists submitted_by text,
    add column if not exists submitted_data jsonb not null default '{}'::jsonb;

update public.verification_vendors
set categories = array[category]
where coalesce(array_length(categories, 1), 0) = 0
  and category is not null
  and btrim(category) <> '';

alter table public.verification_vendor_documents
    add column if not exists mime_type text,
    add column if not exists size_bytes bigint,
    add column if not exists storage_path text;

alter table public.verification_agent_runs
    add column if not exists confidence_score numeric,
    add column if not exists scorecard jsonb not null default '[]'::jsonb;

alter table public.verification_review_decisions
    drop constraint if exists verification_review_decisions_decision_check;

alter table public.verification_review_decisions
    add constraint verification_review_decisions_decision_check
    check (decision in ('APPROVE', 'REJECT', 'REQUEST_INFORMATION'));

create table if not exists public.verification_audit_events (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references public.verification_vendors(id) on delete cascade,
    event_type text not null,
    actor text,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_verification_audit_vendor
    on public.verification_audit_events(vendor_id, created_at desc);

create index if not exists idx_verification_audit_type
    on public.verification_audit_events(event_type);

insert into storage.buckets (id, name, public)
values ('verification-documents', 'verification-documents', false)
on conflict (id) do update set public = excluded.public;

-- Ask PostgREST to refresh its schema cache immediately. This prevents
-- PGRST204 errors such as "Could not find the 'category' column".
notify pgrst, 'reload schema';
