-- Apply this once to an existing Supabase project that already has the
-- vendor-verification MVP schema.

alter table verification_vendors
    add column if not exists region text,
    add column if not exists category text,
    add column if not exists contact_email text,
    add column if not exists compliance_confirmed boolean,
    add column if not exists submitted_by text,
    add column if not exists submitted_data jsonb not null default '{}'::jsonb;

alter table verification_vendor_documents
    add column if not exists mime_type text,
    add column if not exists size_bytes bigint,
    add column if not exists storage_path text;

alter table verification_agent_runs
    add column if not exists confidence_score numeric,
    add column if not exists scorecard jsonb not null default '[]'::jsonb;

alter table verification_review_decisions
    drop constraint if exists verification_review_decisions_decision_check;

alter table verification_review_decisions
    add constraint verification_review_decisions_decision_check
    check (decision in ('APPROVE', 'REJECT', 'REQUEST_INFORMATION'));

create table if not exists verification_audit_events (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references verification_vendors(id) on delete cascade,
    event_type text not null,
    actor text,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_verification_audit_vendor
    on verification_audit_events(vendor_id, created_at desc);

create index if not exists idx_verification_audit_type
    on verification_audit_events(event_type);

insert into storage.buckets (id, name, public)
values ('verification-documents', 'verification-documents', false)
on conflict (id) do update set public = excluded.public;
