create extension if not exists pgcrypto;

create table if not exists company_registry (
    registration_number text primary key,
    legal_name text not null,
    country text,
    registered_address text,
    company_type text,
    registration_status text not null default 'ACTIVE',
    registration_valid_to date,
    source_system text default 'SYNTHETIC_CORPORATE_REGISTRY'
);

create table if not exists tax_registry (
    tax_id text primary key,
    legal_name text not null,
    registration_number text,
    country text,
    tax_status text not null default 'ACTIVE',
    effective_date date,
    cancellation_date date,
    source_system text default 'SYNTHETIC_TAX_REGISTRY'
);

create table if not exists bank_account_registry (
    account_number text not null,
    bank_name text,
    ifsc_swift text,
    account_holder_legal_name text not null,
    account_status text not null default 'ACTIVE',
    name_match_required boolean not null default true,
    source_system text default 'SYNTHETIC_ACCOUNT_VERIFICATION',
    primary key (account_number, ifsc_swift)
);

create table if not exists kyc_registry (
    id bigint generated by default as identity primary key,
    legal_name text not null,
    registration_number text,
    tax_id text,
    kyc_status text not null default 'VERIFIED',
    beneficial_owner_check text default 'CLEAR',
    document_check_status text default 'COMPLETE',
    risk_country_flag boolean default false
);

create index if not exists idx_kyc_registration on kyc_registry(registration_number);
create index if not exists idx_kyc_tax on kyc_registry(tax_id);

create table if not exists sanctions_registry (
    id bigint generated by default as identity primary key,
    entity_name text not null,
    country text,
    match_type text,
    active boolean not null default true,
    reason text,
    source_system text default 'SYNTHETIC_SANCTIONS_SERVICE'
);

create table if not exists vendor_master_snapshot (
    vendor_id text primary key,
    legal_name text not null,
    tax_id text,
    bank_name text,
    account_number text,
    ifsc_swift text,
    country text
);

create index if not exists idx_vendor_master_tax_id on vendor_master_snapshot(tax_id);

create table if not exists verification_vendors (
    id uuid primary key,
    legal_name text not null,
    status text not null,
    agent_recommendation text,
    human_decision text,
    reasons jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists verification_vendor_documents (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references verification_vendors(id) on delete cascade,
    filename text not null,
    document_type text not null,
    confidence numeric,
    extracted_data jsonb not null,
    created_at timestamptz not null default now()
);

create table if not exists verification_agent_runs (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references verification_vendors(id) on delete cascade,
    status text not null,
    recommendation text,
    missing_documents jsonb not null default '[]'::jsonb,
    checks jsonb not null default '[]'::jsonb,
    events jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists verification_review_decisions (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references verification_vendors(id) on delete cascade,
    decision text not null check (decision in ('APPROVE', 'REJECT')),
    reviewer text not null,
    comment text,
    created_at timestamptz not null default now()
);


-- Frontend workflow / case-management extensions.
alter table verification_vendors
    add column if not exists region text,
    add column if not exists category text,
    add column if not exists contact_email text,
    add column if not exists compliance_confirmed boolean,
    add column if not exists submitted_by text,
    add column if not exists submitted_data jsonb not null default '{}'::jsonb;

alter table verification_vendor_documents
    add column if not exists mime_type text,
    add column if not exists size_bytes bigint,
    add column if not exists storage_path text;

alter table verification_agent_runs
    add column if not exists confidence_score numeric,
    add column if not exists scorecard jsonb not null default '[]'::jsonb;

alter table verification_review_decisions
    drop constraint if exists verification_review_decisions_decision_check;

alter table verification_review_decisions
    add constraint verification_review_decisions_decision_check
    check (decision in ('APPROVE', 'REJECT', 'REQUEST_INFORMATION'));

create table if not exists verification_audit_events (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references verification_vendors(id) on delete cascade,
    event_type text not null,
    actor text,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_verification_audit_vendor
    on verification_audit_events(vendor_id, created_at desc);

create index if not exists idx_verification_audit_type
    on verification_audit_events(event_type);

-- Private bucket for original submitted documents. The backend uses its
-- service-role key to upload and returns short-lived signed URLs to reviewers.
insert into storage.buckets (id, name, public)
values ('verification-documents', 'verification-documents', false)
on conflict (id) do update set public = excluded.public;


-- Global enterprise Vendor Master. Only approved onboarding cases are promoted.
create table if not exists vendor_master (
    id uuid primary key default gen_random_uuid(),
    vendor_code text not null unique,
    source_case_id uuid unique references verification_vendors(id) on delete set null,
    legal_name text not null,
    registration_number text,
    tax_id text,
    pan text,
    registered_address text,
    region text,
    categories text[] not null default '{}'::text[],
    primary_contact_name text,
    primary_contact_email text,
    primary_contact_phone text,
    bank_name text,
    account_number text,
    ifsc_swift text,
    bank_verification_status text,
    kyc_status text,
    verification_status text not null default 'VERIFIED',
    risk_level text,
    status text not null default 'ACTIVE'
        check (status in ('ACTIVE', 'SUSPENDED', 'BLOCKED', 'EXPIRED')),
    approved_at timestamptz,
    last_verified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_vendor_master_legal_name on vendor_master(lower(legal_name));
create index if not exists idx_vendor_master_tax on vendor_master(tax_id);
create index if not exists idx_vendor_master_registration on vendor_master(registration_number);
create index if not exists idx_vendor_master_status on vendor_master(status);
create index if not exists idx_vendor_master_categories on vendor_master using gin(categories);

alter table verification_vendors
    add column if not exists categories text[] not null default '{}'::text[],
    add column if not exists contact_name text,
    add column if not exists contact_phone text;

update verification_vendors
set categories = array[category]
where coalesce(array_length(categories, 1), 0) = 0
  and category is not null
  and btrim(category) <> '';

insert into vendor_master (
    vendor_code, source_case_id, legal_name, tax_id, pan,
    registered_address, region, categories,
    primary_contact_name, primary_contact_email, primary_contact_phone,
    account_number, ifsc_swift, verification_status, status,
    approved_at, last_verified_at
)
select
    'VEN-' || upper(substr(replace(v.id::text, '-', ''), 1, 8)),
    v.id,
    v.legal_name,
    nullif(v.submitted_data->>'tax_id', ''),
    nullif(v.submitted_data->>'pan', ''),
    nullif(v.submitted_data->>'registered_address', ''),
    v.region,
    case
        when jsonb_typeof(v.submitted_data->'categories') = 'array'
        then array(select jsonb_array_elements_text(v.submitted_data->'categories'))
        when v.category is not null and btrim(v.category) <> ''
        then array[v.category]
        else '{}'::text[]
    end,
    nullif(v.submitted_data->>'contact_name', ''),
    coalesce(nullif(v.submitted_data->>'contact_email', ''), v.contact_email),
    nullif(v.submitted_data->>'contact_phone', ''),
    nullif(v.submitted_data->>'bank_account', ''),
    nullif(v.submitted_data->>'ifsc', ''),
    case when v.human_decision = 'APPROVE' then 'VERIFIED_WITH_OVERRIDE' else 'VERIFIED' end,
    'ACTIVE',
    v.updated_at,
    v.updated_at
from verification_vendors v
where v.status = 'APPROVED'
on conflict (source_case_id) do nothing;
