create extension if not exists pgcrypto;

create table if not exists company_registry (
    registration_number text primary key,
    legal_name text not null,
    country text,
    registered_address text,
    company_type text,
    registration_status text not null default 'ACTIVE',
    registration_valid_to date,
    source_system text default 'SYNTHETIC_CORPORATE_REGISTRY'
);

create table if not exists tax_registry (
    tax_id text primary key,
    legal_name text not null,
    registration_number text,
    country text,
    tax_status text not null default 'ACTIVE',
    effective_date date,
    cancellation_date date,
    source_system text default 'SYNTHETIC_TAX_REGISTRY'
);

create table if not exists bank_account_registry (
    account_number text not null,
    bank_name text,
    ifsc_swift text,
    account_holder_legal_name text not null,
    account_status text not null default 'ACTIVE',
    name_match_required boolean not null default true,
    source_system text default 'SYNTHETIC_ACCOUNT_VERIFICATION',
    primary key (account_number, ifsc_swift)
);

create table if not exists kyc_registry (
    id bigint generated by default as identity primary key,
    legal_name text not null,
    registration_number text,
    tax_id text,
    kyc_status text not null default 'VERIFIED',
    beneficial_owner_check text default 'CLEAR',
    document_check_status text default 'COMPLETE',
    risk_country_flag boolean default false
);

create index if not exists idx_kyc_registration on kyc_registry(registration_number);
create index if not exists idx_kyc_tax on kyc_registry(tax_id);

create table if not exists sanctions_registry (
    id bigint generated by default as identity primary key,
    entity_name text not null,
    country text,
    match_type text,
    active boolean not null default true,
    reason text,
    source_system text default 'SYNTHETIC_SANCTIONS_SERVICE'
);

create table if not exists vendor_master_snapshot (
    vendor_id text primary key,
    legal_name text not null,
    tax_id text,
    bank_name text,
    account_number text,
    ifsc_swift text,
    country text
);

create index if not exists idx_vendor_master_tax_id on vendor_master_snapshot(tax_id);

create table if not exists vendors (
    id uuid primary key,
    legal_name text not null,
    status text not null,
    agent_recommendation text,
    human_decision text,
    reasons jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists vendor_documents (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references vendors(id) on delete cascade,
    filename text not null,
    document_type text not null,
    confidence numeric,
    extracted_data jsonb not null,
    created_at timestamptz not null default now()
);

create table if not exists agent_runs (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references vendors(id) on delete cascade,
    status text not null,
    recommendation text,
    missing_documents jsonb not null default '[]'::jsonb,
    checks jsonb not null default '[]'::jsonb,
    events jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists review_decisions (
    id bigint generated by default as identity primary key,
    vendor_id uuid not null references vendors(id) on delete cascade,
    decision text not null check (decision in ('APPROVE', 'REJECT')),
    reviewer text not null,
    comment text,
    created_at timestamptz not null default now()
);
