from typing import Protocol, runtime_checkable

from app.schemas.domain import (
    AgentRun,
    Approval,
    AuditEvent,
    Document,
    ExtractedFieldRecord,
    FindingRecord,
    PODraftRecord,
    RiskAssessmentRecord,
    SanctionsEntry,
    Vendor,
    VendorDraftRecord,
    VendorRequest,
)


@runtime_checkable
class OnboardingRepository(Protocol):
    def create_request(self, request: VendorRequest) -> VendorRequest: ...
    def get_request(self, request_id: str) -> VendorRequest | None: ...
    def list_requests(self) -> list[VendorRequest]: ...
    def set_request_status(self, request_id: str, new_status: str, actor: str, reason: str) -> VendorRequest: ...
    def add_document(self, document: Document) -> Document: ...
    def list_documents(self, request_id: str) -> list[Document]: ...
    def save_extracted_fields(self, request_id: str, document_id: str, fields: list[ExtractedFieldRecord]) -> list[ExtractedFieldRecord]: ...
    def list_extracted_fields(self, request_id: str) -> list[ExtractedFieldRecord]: ...
    def save_findings(self, request_id: str, source: str, findings: list[FindingRecord]) -> list[FindingRecord]: ...
    def list_findings(self, request_id: str) -> list[FindingRecord]: ...
    def save_risk_assessment(self, assessment: RiskAssessmentRecord) -> RiskAssessmentRecord: ...
    def get_latest_risk_assessment(self, request_id: str) -> RiskAssessmentRecord | None: ...
    def add_approval(self, approval: Approval) -> Approval: ...
    def list_approvals(self, request_id: str) -> list[Approval]: ...
    def append_audit_event(self, event: AuditEvent) -> AuditEvent: ...
    def list_audit_events(self, request_id: str | None = None) -> list[AuditEvent]: ...
    def list_vendors(self) -> list[Vendor]: ...
    def list_sanctions_entries(self) -> list[SanctionsEntry]: ...
    def save_agent_run(self, run: AgentRun) -> AgentRun: ...
    def save_vendor_draft(self, draft: VendorDraftRecord) -> VendorDraftRecord: ...
    def get_vendor_draft(self, request_id: str) -> VendorDraftRecord | None: ...
    def save_po_draft(self, draft: PODraftRecord) -> PODraftRecord: ...
    def get_po_draft(self, request_id: str) -> PODraftRecord | None: ...
